Fixed error causing compile fail on clang++
Error was:
./SimpleGraphs.hpp:520:15: error: non-const lvalue reference to type 'unordered_map<...>' cannot bind to a temporary of type 'unordered_map<...>'
auto& neighborList = g.getNeighbors();